services:
  pizza-website:
    image: agigglesniffer/buddyspizza:latest
    container_name: pizza-website
    ports:
      - "4080:4080"
    restart: unless-stopped
    enviroment:
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      drizzle-db:
        condition: service_healthy

  drizzle-db:
    image: postgres:15-alpine
    container_name: drizzle-db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    expose: "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seed:
    image: agigglesniffer/buddyspizza-seed:latest
    depends_on:
      drizzle-db:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE="0 0 3 * * *" # everyday at 3am

volumes:
  postgres_data:
