services:
  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@drizzle-db:5432/mydatabase
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
    networks:
      - shared-net
    restart: "no"

networks:
  shared-net:
    external: true
    name: drizzle-db_shared-net